spring.application.name=ai
server.port=2626

spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.model=qwen3:8b
spring.ai.ollama.chat.model=mistral

spring.datasource.url= jdbc:mysql://localhost:3306/ai
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


